import type { EventItem } from "./types";

export const seedEvents: EventItem[] = [
  // =======================
  // کنسرت‌ها - تهران
  // =======================
  {
    id: 1,
    slug: "concert-arman-tehran",
    title: "کنسرت آرمان در تهران",
    city: "تهران",
    category: "کنسرت",
    date: "1405/05/12",
    time: "20:00",
    place: "سالن میلاد",
    price: "از ۳۵۰ هزار تومان",
    image: "/images/placeholder-event.svg",
    badge: "پرفروش",
    popular: true,
  },
  {
    id: 2,
    slug: "pop-music-night-tehran",
    title: "شب موسیقی پاپ",
    city: "تهران",
    category: "کنسرت",
    date: "1405/05/15",
    time: "21:00",
    place: "ایوان شمس",
    price: "از ۲۸۰ هزار تومان",
    image: "/images/placeholder-event.svg",
    badge: "ویژه",
  },
  {
    id: 3,
    slug: "live-negahme-tehran",
    title: "اجرای زنده نغمه",
    city: "تهران",
    category: "کنسرت",
    date: "1405/05/18",
    time: "19:30",
    place: "برج آزادی",
    price: "از ۳۰۰ هزار تومان",
    image: "/images/placeholder-event.svg",
  },
  {
    id: 4,
    slug: "summer-concert-tehran",
    title: "کنسرت تابستانی",
    city: "تهران",
    category: "کنسرت",
    date: "1405/05/20",
    time: "20:30",
    place: "سالن همایش‌ها",
    price: "از ۴۰۰ هزار تومان",
    image: "/images/placeholder-event.svg",
  },
  {
    id: 5,
    slug: "nostalgic-music-night-tehran",
    title: "شب خاطره‌انگیز موسیقی",
    city: "تهران",
    category: "کنسرت",
    date: "1405/05/22",
    time: "21:15",
    place: "فرهنگسرای نیاوران",
    price: "از ۲۵۰ هزار تومان",
    image: "/images/placeholder-event.svg",
    badge: "جدید",
  },
  {
    id: 6,
    slug: "stars-group-concert-tehran",
    title: "کنسرت گروه ستاره‌ها",
    city: "تهران",
    category: "کنسرت",
    date: "1405/05/24",
    time: "19:45",
    place: "تالار وحدت",
    price: "از ۴۵۰ هزار تومان",
    image: "/images/placeholder-event.svg",
  },
  {
    id: 7,
    slug: "rainy-night-live-tehran",
    title: "اجرای زنده شب بارانی",
    city: "تهران",
    category: "کنسرت",
    date: "1405/05/26",
    time: "20:15",
    place: "مجموعه ایران‌مال",
    price: "از ۳۲۰ هزار تومان",
    image: "/images/placeholder-event.svg",
  },
  {
    id: 8,
    slug: "acoustic-concert-tehran",
    title: "کنسرت آکوستیک",
    city: "تهران",
    category: "کنسرت",
    date: "1405/05/28",
    time: "18:30",
    place: "خانه هنرمندان",
    price: "از ۲۷۰ هزار تومان",
    image: "/images/placeholder-event.svg",
  },
  {
    id: 9,
    slug: "night-music-tehran",
    title: "موسیقی شبانه",
    city: "تهران",
    category: "کنسرت",
    date: "1405/05/30",
    time: "22:00",
    place: "کاخ نیاوران",
    price: "از ۵۰۰ هزار تومان",
    image: "/images/placeholder-event.svg",
    badge: "پیشنهاد ویژه",
  },
  {
    id: 10,
    slug: "spring-concert-tehran",
    title: "کنسرت بهار",
    city: "تهران",
    category: "کنسرت",
    date: "1405/06/02",
    time: "20:00",
    place: "پردیس تئاتر",
    price: "از ۳۸۰ هزار تومان",
    image: "/images/placeholder-event.svg",
  },

  // =======================
  // تئاتر - تهران
  // =======================
  {
    id: 11,
    slug: "last-night-theater-tehran",
    title: "نمایش شب آخر",
    city: "تهران",
    category: "تئاتر",
    date: "1405/05/12",
    time: "18:00",
    place: "تماشاخانه ایرانشهر",
    price: "از ۱۵۰ هزار تومان",
    image: "/images/placeholder-event.svg",
    badge: "ویژه",
  },
  {
    id: 12,
    slug: "shadows-theater-tehran",
    title: "تئاتر سایه‌ها",
    city: "تهران",
    category: "تئاتر",
    date: "1405/05/14",
    time: "19:00",
    place: "پردیس شهرزاد",
    price: "از ۱۷۰ هزار تومان",
    image: "/images/placeholder-event.svg",
  },
  {
    id: 13,
    slug: "comedy-show-tehran",
    title: "نمایش خنده‌دار",
    city: "تهران",
    category: "تئاتر",
    date: "1405/05/16",
    time: "20:00",
    place: "تالار مولوی",
    price: "از ۱۳۰ هزار تومان",
    image: "/images/placeholder-event.svg",
  },
  {
    id: 14,
    slug: "rainy-day-theater-tehran",
    title: "تئاتر یک روز بارانی",
    city: "تهران",
    category: "تئاتر",
    date: "1405/05/18",
    time: "18:30",
    place: "تماشاخانه سنگلج",
    price: "از ۲۰۰ هزار تومان",
    image: "/images/placeholder-event.svg",
  },
  {
    id: 15,
    slug: "old-letters-theater-tehran",
    title: "نمایش نامه‌های قدیمی",
    city: "تهران",
    category: "تئاتر",
    date: "1405/05/20",
    time: "19:30",
    place: "خانه هنرمندان",
    price: "از ۱۶۰ هزار تومان",
    image: "/images/placeholder-event.svg",
    badge: "پرفروش",
  },
  {
    id: 16,
    slug: "contemporary-theater-mashhad",
    title: "تئاتر معاصر",
    city: "مشهد",
    category: "تئاتر",
    date: "1405/05/22",
    time: "21:00",
    place: "فرهنگسرای نیاوران",
    price: "از ۱۴۰ هزار تومان",
    image: "/images/placeholder-event.svg",
  },
  {
    id: 17,
    slug: "dreamlike-show-mashhad",
    title: "نمایش شبیه رویا",
    city: "مشهد",
    category: "تئاتر",
    date: "1405/05/24",
    time: "18:45",
    place: "پردیس تئاتر",
    price: "از ۱۹۰ هزار تومان",
    image: "/images/placeholder-event.svg",
  },
  {
    id: 18,
    slug: "frame-theater-mashhad",
    title: "تئاتر قاب",
    city: "مشهد",
    category: "تئاتر",
    date: "1405/05/26",
    time: "19:15",
    place: "تئاتر باران",
    price: "از ۱۸۰ هزار تومان",
    image: "/images/placeholder-event.svg",
  },
  {
    id: 19,
    slug: "final-season-theater-shiraz",
    title: "نمایش فصل آخر",
    city: "شیراز",
    category: "تئاتر",
    date: "1405/05/28",
    time: "20:15",
    place: "تالار وحدت",
    price: "از ۲۲۰ هزار تومان",
    image: "/images/placeholder-event.svg",
    badge: "جدید",
  },
  {
    id: 20,
    slug: "city-theater-shiraz",
    title: "تئاتر شهر",
    city: "شیراز",
    category: "تئاتر",
    date: "1405/06/01",
    time: "18:15",
    place: "تئاتر شهر",
    price: "از ۱۶۵ هزار تومان",
    image: "/images/placeholder-event.svg",
  },

  // =======================
  // ایونت — کافه / گالری / موزه / ورک‌شاپ
  // =======================
  {
    id: 21,
    slug: "live-music-cafe-niloufar-tehran",
    title: "شب موسیقی زنده در کافه نیلوفر",
    city: "تهران",
    category: "ایونت",
    date: "1405/05/14",
    time: "20:00",
    place: "کافه نیلوفر",
    price: "از ۱۸۰ هزار تومان",
    image: "/images/placeholder-event.svg",
    badge: "جدید",
    ticketingType: "INTERNAL",
  },
  {
    id: 22,
    slug: "photo-exhibition-gallery-art-isfahan",
    title: "نمایشگاه عکس معاصر در گالری آرت",
    city: "اصفهان",
    category: "ایونت",
    date: "1405/05/16",
    time: "17:00",
    place: "گالری هنرهای تجسمی آرت",
    price: "از ۱۲۰ هزار تومان",
    image: "/images/placeholder-event.svg",
    ticketingType: "INTERNAL",
  },
  {
    id: 23,
    slug: "watercolor-workshop-museum-shiraz",
    title: "ورک‌شاپ نقاشی آبرنگ در موزه هنر",
    city: "شیراز",
    category: "ایونت",
    date: "1405/05/18",
    time: "16:30",
    place: "موزه هنرهای معاصر شیراز",
    price: "از ۲۵۰ هزار تومان",
    image: "/images/placeholder-event.svg",
    badge: "پیشنهاد ویژه",
    ticketingType: "INTERNAL",
  },
  {
    id: 24,
    slug: "poetry-music-night-cafe-book-mashhad",
    title: "شب شعر و موسیقی در کافه کتاب",
    city: "مشهد",
    category: "ایونت",
    date: "1405/05/20",
    time: "19:00",
    place: "کافه کتاب مشهد",
    price: "از ۱۵۰ هزار تومان",
    image: "/images/placeholder-event.svg",
    ticketingType: "INTERNAL",
  },
  {
    id: 25,
    slug: "gallery-tour-meet-artist-tabriz",
    title: "تور گالری و ملاقات با هنرمند",
    city: "تبریز",
    category: "ایونت",
    date: "1405/05/22",
    time: "18:00",
    place: "گالری هنرهای تجسمی تبریز",
    price: "از ۹۰ هزار تومان",
    image: "/images/placeholder-event.svg",
    ticketingType: "INTERNAL",
  },
  {
    id: 26,
    slug: "street-photography-workshop-tehran",
    title: "کارگاه عکاسی خیابانی",
    city: "تهران",
    category: "ایونت",
    date: "1405/05/24",
    time: "09:30",
    place: "خانه عکاسان تهران",
    price: "از ۳۲۰ هزار تومان",
    image: "/images/placeholder-event.svg",
    badge: "ظرفیت محدود",
    popular: true,
    ticketingType: "INTERNAL",
  },
];
